import assert from 'node:assert/strict';
import {STEPS,createSeed,visibleJobs,removeCustomer,validateUsername,passwordRecord,verifyPassword,stepTitle,progress} from '../dist/data.js';
const state=await createSeed();
assert.equal(STEPS.length,15);
assert.equal(await verifyPassword('Admin1234',state.admin.password),true);
assert.equal(await verifyPassword('incorrect',state.admin.password),false);
assert.equal(visibleJobs(state,{id:'c1',role:'customer'}).length,2);
assert.ok(visibleJobs(state,{id:'c1',role:'customer'}).every(j=>j.customerId==='c1'));
assert.equal(visibleJobs(state,{id:'admin',role:'admin'}).length,4);
assert.equal(validateUsername(state,'SIAM'),false);
assert.equal(validateUsername(state,'Admin'),false);
assert.equal(validateUsername(state,'SIAM','c1'),true);
const record=await passwordRecord('Changed1234');
assert.equal(await verifyPassword('Changed1234',record),true);
assert.equal(await verifyPassword('Demo1234',record),false);
assert.equal(stepTitle(STEPS.find(s=>s.id==='B2'),state.jobs.find(j=>j.permit==='มอ.5')),'อยู่ระหว่างนำเข้า');
const j=state.jobs[0],before=j.steps.B3.status;j.steps.A2.status='done';
assert.equal(j.steps.B3.status,before);
assert.equal(progress(j).done,8);
removeCustomer(state,'c1');
assert.ok(state.jobs.every(j=>j.customerId!=='c1'));
assert.ok(state.customers.every(c=>c.id!=='c1'));
console.log('PASS: 15 stations, demo login, password reset, customer scoping, duplicate usernames, parallel branches, permit labels, and deletion.');
